export const DEMO_COMMITS = [
  { hash: 'a1b2c3d', message: 'feat: add user authentication with JWT', date: '2025-06-02', repo: 'web-app', author: 'Developer' },
  { hash: 'b2c3d4e', message: 'feat: create dashboard with analytics charts', date: '2025-06-03', repo: 'web-app', author: 'Developer' },
  { hash: 'c3d4e5f', message: 'fix: resolve login redirect loop on mobile', date: '2025-06-03', repo: 'web-app', author: 'Developer' },
  { hash: 'd4e5f6a', message: 'feat: integrate payment gateway (Midtrans)', date: '2025-06-04', repo: 'web-app', author: 'Developer' },
  { hash: 'e5f6a7b', message: 'fix: fix checkout total calculation bug', date: '2025-06-04', repo: 'web-app', author: 'Developer' },
  { hash: 'f6a7b8c', message: 'chore: update dependencies and security patches', date: '2025-06-05', repo: 'web-app', author: 'Developer' },
  { hash: 'a7b8c9d', message: 'feat: add email notification system', date: '2025-06-05', repo: 'api-service', author: 'Developer' },
  { hash: 'b8c9d0e', message: 'improve: optimize database queries for product listing', date: '2025-06-06', repo: 'api-service', author: 'Developer' },
  { hash: 'c9d0e1f', message: 'feat: add product search with filters', date: '2025-06-07', repo: 'web-app', author: 'Developer' },
  { hash: 'd0e1f2a', message: 'fix: fix image upload not working on Safari', date: '2025-06-08', repo: 'web-app', author: 'Developer' },
  { hash: 'e1f2a3b', message: 'feat: implement order tracking page', date: '2025-06-09', repo: 'web-app', author: 'Developer' },
  { hash: 'f2a3b4c', message: 'improve: redesign mobile navigation', date: '2025-06-09', repo: 'web-app', author: 'Developer' },
  { hash: 'a3b4c5d', message: 'feat: add admin panel for order management', date: '2025-06-10', repo: 'admin-panel', author: 'Developer' },
  { hash: 'b4c5d6e', message: 'fix: resolve API rate limiting issue', date: '2025-06-10', repo: 'api-service', author: 'Developer' },
  { hash: 'c5d6e7f', message: 'feat: add export to CSV for reports', date: '2025-06-11', repo: 'admin-panel', author: 'Developer' },
  { hash: 'd6e7f8a', message: 'improve: add loading skeletons throughout UI', date: '2025-06-12', repo: 'web-app', author: 'Developer' },
  { hash: 'e7f8a9b', message: 'feat: implement push notifications', date: '2025-06-13', repo: 'api-service', author: 'Developer' },
  { hash: 'f8a9b0c', message: 'fix: fix memory leak in background job processor', date: '2025-06-14', repo: 'api-service', author: 'Developer' },
  { hash: 'a9b0c1d', message: 'chore: setup CI/CD pipeline with GitHub Actions', date: '2025-06-15', repo: 'web-app', author: 'Developer' },
  { hash: 'b0c1d2e', message: 'feat: add multi-language support (ID/EN)', date: '2025-06-16', repo: 'web-app', author: 'Developer' },
  { hash: 'c1d2e3f', message: 'improve: enhance SEO meta tags and sitemap', date: '2025-06-17', repo: 'web-app', author: 'Developer' },
  { hash: 'd2e3f4a', message: 'fix: fix order status not updating in real-time', date: '2025-06-18', repo: 'api-service', author: 'Developer' },
  { hash: 'e3f4a5b', message: 'feat: add referral program module', date: '2025-06-19', repo: 'web-app', author: 'Developer' },
  { hash: 'f4a5b6c', message: 'feat: add transaction history with filters', date: '2025-06-20', repo: 'admin-panel', author: 'Developer' },
  { hash: 'a5b6c7d', message: 'improve: add dark mode support', date: '2025-06-21', repo: 'web-app', author: 'Developer' },
  { hash: 'b6c7d8e', message: 'fix: fix incorrect tax calculation for certain products', date: '2025-06-22', repo: 'api-service', author: 'Developer' },
  { hash: 'c7d8e9f', message: 'feat: integrate Google Analytics', date: '2025-06-23', repo: 'web-app', author: 'Developer' },
  { hash: 'd8e9f0a', message: 'chore: refactor authentication middleware', date: '2025-06-24', repo: 'api-service', author: 'Developer' },
  { hash: 'e9f0a1b', message: 'improve: add input validation and error messages', date: '2025-06-25', repo: 'web-app', author: 'Developer' },
  { hash: 'f0a1b2c', message: 'feat: add webhook support for third-party integrations', date: '2025-06-25', repo: 'api-service', author: 'Developer' },
]

export const DEMO_REPORT_CONFIG = {
  title: 'Laporan Perkembangan IT - Juni 2025',
  startDate: '2025-06-01',
  endDate: '2025-06-30',
  repos: ['web-app', 'api-service', 'admin-panel'],
  sections: ['kop', 'periode', 'highlight_stats', 'executive_summary', 'key_highlights', 'issues_resolved', 'weekly_summary', 'developer_info'],
}
